выводит категории пользователя
htmlacademy-yii/164719-task-force-1 pull request #12
Opened 2020-06-14 17:48 UTC by zbralex

2020-07-15 04:59 UTC, b1rdex requested changes
Вьюхи не проверял

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m130524_201442_init.php
>      }
Эту миграцию наверное стоит вообще удалить, т.к. она ничего не делает

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m190124_110200_add_verification_token_column_to_user_table.php
> +        //$this->addColumn('{{%user}}', 'verification_token', $this->string()->defaultValue(null));
Эту тоже наверно лучше удалить

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m200706_083022_add_online_column_to_userInfo.php
> +    */
```suggestion
```
Этот мусор лучше не оставлять

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m200709_154427_drop_pk_executor_id_table_task.php
> +    */
```suggestion
```

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m200709_154427_drop_pk_executor_id_table_task.php
> +		    'task_ibfk_3',
Я вижу ты его из дампа тоже удалил, миграция не пройдёт

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m200713_091801_change_executor_id_default_null.php
> +    */
```suggestion
```

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m200714_191333_drop_and_add_column_city_id_table_task.php
> +		$this->alterColumn('task', 'city_id', $this->string()->null());
тут integer

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m200714_191333_drop_and_add_column_city_id_table_task.php
> +    */
```suggestion
```

2020-07-15 04:59 UTC, b1rdex commented on console/migrations/m200714_194950_foreign_kye_column_city_id_table_task.php
> +    */
```suggestion
```

2020-07-15 04:59 UTC, b1rdex commented on frontend/views/layouts/main.php
> +                        <a href="/tasks">Задания</a>
Ссылки делаем через url to

2020-07-15 04:59 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +		if ($filter->load(Yii::$app->request->post())) {
Думаю фильтр должен быть get, чтобы можно было поделиться ссылкой

2020-07-15 04:59 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +			$task = (new Task)->filterForm($formContent);
Так у тебя получается, что таски выбираются из БД два раза. Можно сделать чтобы они выбирались один раз через этот метод всегда, даже если фильтр пустой?

2020-07-15 04:59 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +		$detail = Task::findOne($id);
Если нет такого таска, то нужно отдать 404

2020-07-15 04:59 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +		if ($filter->load(Yii::$app->request->post())) {
То же самое про post

2020-07-15 04:59 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +			$user = (new UserInfo)->filterForm($formContent);
То же самое про два запроса

2020-07-15 04:59 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +		$detail = UserInfo::findOne($id);
То же самое про 404

2020-07-15 04:59 UTC, b1rdex commented on frontend/models/Task.php
> +    public function getCities()
Тут всегда один город, не стоит именовать в множественном числе

2020-07-15 04:59 UTC, b1rdex commented on frontend/models/Task.php
> +			->limit(3)->orderBy('created_at ASC');
Зачем лимит?

2020-07-15 04:59 UTC, b1rdex commented on frontend/models/Task.php
> +	public function filterForm($value)
Стоит добавить тип к $value, чтобы IDE показывала правильно тип

2020-07-15 04:59 UTC, b1rdex commented on frontend/models/UserInfo.php
> +	public function filterForm($value)
Тут я бы тоже добавил тип формы

2020-07-15 04:59 UTC, b1rdex commented on frontend/models/UserInfo.php
> +			->limit(5)->orderBy('u.created_at ASC');
Зачем лимит?

2020-07-15 04:59 UTC, b1rdex commented on frontend/models/forms/TaskForm.php
> +	public $search;
Тут стоит добавить валидацию через rules() (и нужно будет вызывать validate(), если этого ещё нет в контроллере), чтобы что попало не отправлять в запросы к бд

2020-07-15 04:59 UTC, b1rdex commented on frontend/models/forms/UserForm.php
> +//    }
Нужно сделать валидацию как и в тасках

2020-07-15 07:12 UTC, zbralex commented on frontend/models/UserInfo.php
> +			->limit(5)->orderBy('u.created_at ASC');
https://up.htmlacademy.ru/yii/1/project/task-force#taskforce-6-6
Там в самом конце:
_На странице показывается максимум пять исполнителей. При большем числе записей следует показывать их через пагинацию._

Могу убрать пока

2020-07-17 05:05 UTC, b1rdex requested changes
Так, про ошибки валидации фильтра: у тебя там всё safe, так что можешь на них забить. Удали тогда с контроллера var_dump/die и на этом остановимся

2020-07-17 05:05 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +		$detail = Task::findOne($id);
Актуально

2020-07-17 05:05 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +			$tasks = (new Task)->filterForm($formContent);
Я когда писал про типы в filterForm, думал ты туда форму передаёшь.
Думаю лучше туда передавать заполненную форму и с ней уже работать

2020-07-17 05:05 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +				die;
Не очень хороший финал валидации :) надо либо показывать эти ошибки на странице (можно прям в фильтре, если там есть под это вёрстка), либо внутри filterForm() проверять что поле без ошибок (`!$form->hasError('field name')`) и только в этом случае применять поле для фильтра

2020-07-17 05:05 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +			->where(['status' => 'new'])
Могу ошибаться, но, по-моему, `new` должно быть через константу

2020-07-17 05:05 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +				die;
Тут надо тоже что-то придумать с ошибками

2020-07-17 05:05 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +			$users = (new UserInfo)->filterForm($formContent);
Тут предлагаю тоже фильтр передавать как объект

2020-07-17 05:05 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +		$detail = UserInfo::findOne($id);
Про 404 актуально

2020-07-17 05:05 UTC, b1rdex commented on frontend/models/Task.php
>  		foreach ($value as $key => $item) {
Если сюда передать объект, то можно под каждое поле написать отдельный if, либо оставить как сейчас — вроде форма Traversible. Если не Traversible, то можно сделать ->getAttributes()

2020-07-17 05:05 UTC, b1rdex commented on frontend/views/tasks/view.php
> +                                   <?= Yii::$app->formatter->asRelativeTime(strtotime('-3 hour', strtotime($detail->created_at))) ?></span>
Откуда -3 часа?

2020-07-17 10:01 UTC, zbralex commented on frontend/controllers/UsersController.php
> +				die;
Пока ничего не придумал, просто убрал:
```
var_dump($errors);
die;
```

2020-07-17 10:07 UTC, zbralex commented on frontend/views/tasks/view.php
> +                                   <?= Yii::$app->formatter->asRelativeTime(strtotime('-3 hour', strtotime($detail->created_at))) ?></span>
У меня все даты отображаются без часового пояса. Я подумал, что у тебя будет отображено московское время и ты завернешь на доработку времени. Поэтому убрал в конфиге  часовой пояс 
`'timeZone' => 'Europe/Moscow'`
Просто сейчас в задачах нет пояснения по часовому поясу. Как сделать? Оставить так, или включить часовой пояс Москва и убрать -3 часа?

2020-07-17 14:59 UTC, zbralex commented on frontend/models/Task.php
>  		foreach ($value as $key => $item) {
а зачем нам писать под каждое поле if, если есть switch?
Я могу переписать это, перенеся в контроллер. Все равно не понял про объект(

2020-07-17 15:10 UTC, zbralex commented on frontend/models/Task.php
>  		foreach ($value as $key => $item) {
в общем, я перенес код по обработке полей формы в контроллер, в последнем коммите можно увидеть все изменения

2020-07-23 07:26 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +		if (empty($detail)) {
Я замержу, исправь потом: это нужно доднять выше, сразу после findOne(). Сейчас возможна ошибка в `$user_created_at = User::findOne($detail->author_id);`, т.к $detail can be null.

2020-07-23 07:27 UTC, b1rdex commented on frontend/views/tasks/view.php
> +                                   <?= Yii::$app->formatter->asRelativeTime(strtotime('-3 hour', strtotime($detail->created_at))) ?></span>
Я думаю стоит убрать -3 часа, пусть показывает в часовом поясе сервера

2020-07-23 07:28 UTC, merged