добавляет accessController
htmlacademy-yii/164719-task-force-1 pull request #15
Opened 2020-08-04 05:36 UTC by zbralex

2020-08-07 08:20 UTC, b1rdex requested changes

2020-08-07 08:20 UTC, b1rdex commented on frontend/controllers/SecuredController.php
> +class SecuredController extends Controller
abstract

2020-08-07 08:20 UTC, b1rdex commented on frontend/views/layouts/landing.php
> +use frontend\models;
```suggestion
use frontend\assets\AppAsset;
```

2020-08-13 10:28 UTC, b1rdex requested changes

2020-08-13 10:28 UTC, b1rdex commented on frontend/controllers/SignUpController.php
>          $model = new User();
Тут нужно добавить проверку, что пользователь неавторизован. Если авторизован, то редиректить на home

2020-08-13 10:28 UTC, b1rdex commented on frontend/controllers/LandingController.php
> +		$model = new LoginForm();
Если залогиненный пользователь открывает главную страницу (/), то его всегда переадресует на просмотр заданий.

2020-08-15 10:23 UTC, zbralex commented on frontend/controllers/LandingController.php
> +		$model = new LoginForm();
сделал

2020-08-15 10:55 UTC, zbralex commented on frontend/controllers/SignUpController.php
>          $model = new User();
Здесь сложно как-то. У меня для этого класса используется behaviors(), а он просто запрещает доступ залогиненным через массив правил. Я написал с помощью beforeAction. В следующих коммитах увидишь. Думаю, что есть решение более правильное

2020-08-17 07:08 UTC, b1rdex requested changes
Проверки на доступ без авторизации надо переделать без beforeAction и behavior.

2020-08-17 09:36 UTC, merged