удаляет файлы upload
htmlacademy-yii/164719-task-force-1 pull request #16
Opened 2020-08-17 12:35 UTC by zbralex

2020-08-28 05:36 UTC, b1rdex commented on frontend/views/tasks/view.php
> +$user_data =  User::findOne(Yii::$app->user->id);
`Yii::$app->user` вроде и так instanceof User?

2020-08-31 08:51 UTC, zbralex commented on frontend/views/tasks/view.php
> +$user_data =  User::findOne(Yii::$app->user->id);
Здесь получилось как-то неоднозначно с таблицами.
У меня две таблицы _user_ и _user_info_.
 При регистрации нового пользователя в форме регистрации есть одно поле: "Имя и фамилия", данные сохраняются в таблицу **user**.
Однако, у меня есть таблица _user_info_, в которой есть отдельные поля ИМЯ и ФАМИЛИЯ. 
После авторизации необходимо как-то вывести имя и фамилию в профиле в шапке, иначе ошибка. То есть, по умолчанию выводится поле _name_ из таблицы _user_, если заполнить поля в таблице _user_info_, будут отображены они.

2020-09-02 05:05 UTC, b1rdex commented on frontend/views/tasks/view.php
> +$user_data =  User::findOne(Yii::$app->user->id);
Я там первый раз ошибся, так верно: `Yii::$app->user->identity` – это текущий User. В этой модели у тебя должен быть relation, по которому можно получить профиль из user_info.

2020-09-02 08:45 UTC, b1rdex requested changes

2020-09-02 08:45 UTC, b1rdex commented on frontend/views/signup/index.php
> +                        'class' => $model->getErrors('password') ?? 'input-danger'
Тут похоже ошибка. Не думаю, что в класс стоит писать текст ошибки поля password.

2020-09-02 08:45 UTC, b1rdex commented on frontend/views/tasks/create.php
> +CreateTaskDropZone::register($this);
Давай пока закомментируем, чтобы перетаксивание файлов не сабмитило форму
```suggestion
// CreateTaskDropZone::register($this);
```

2020-09-02 08:45 UTC, b1rdex commented on frontend/views/tasks/view.php
> +                                                echo $detail->author->name . ' ' . $detail->author->surname;
Я тут просто напишу, сейчас всё не обязательно переделывать, но имей ввиду: в требованиях есть пункт, что весь пользовательский ввод должен экранироваться при выводе, чтобы защититься от XSS.

Для этого используется Html::encode(), т.е. например, тут надо сделать `Html::encode($detail->author->name . ' ' . $detail->author->surname)`

2020-09-02 08:45 UTC, b1rdex commented on src/classes/Task.php
> +            case self::STATUS_NEW and $role == 1:
Я больше конечно за текстовый вариант, было понятно хотя бы. Но хоть текст, хоть цифры, нужно поменять на константы.

2020-09-02 08:45 UTC, b1rdex commented on src/classes/Task.php
> +            case self::STATUS_PROGRESS and $role == 2:
Тут тоже

2020-09-02 08:45 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +            FilterUtil::formFilter($formContent, $query);
Тут вариантов два. Либо а) верни как было, т.к. это не бизнес логика, а формирование списка. Либо б) вынеси полностью получение пользователей в сервис – вызываешь метод, передавая туда форму, а он тебе в ответ возвращает уже готовый query, на который остаётся только вызывать `->all()`. Возвращать именно query, а не массив пользователей нужно из-за того, что в будущем вы тут будете менять массив на дата провайдер, а для него нужен query.

2020-09-02 08:45 UTC, b1rdex commented on src/classes/utils/FilterUtil.php
> +abstract class FilterUtil {
Как уже написал в контроллере, с этим надо что-то сделать

2020-09-02 08:45 UTC, b1rdex commented on src/classes/utils/CreateTaskService.php
> +abstract class CreateTaskService
В целом, это конечно дело вкуса, но я бы тут не делал класс абстрактным и использовал не статический метод. Но это на твоё усмотрение, в таком виде всё тоже верно.

2020-09-02 08:45 UTC, b1rdex commented on frontend/views/tasks/create.php
> + * */
Строчки с `$var = []` неправильные, а последняя `@var` не имеет указания тип. Должен быть такой синтаксис: `@var тип-переменной $имя-переменной` для каждой переменной в новой строке. Т.е. так:
```
 /**
  * @var string[] $categories
  * @var array $errors
  */
```

2020-09-02 10:44 UTC, zbralex commented on frontend/views/tasks/view.php
> +                                                echo $detail->author->name . ' ' . $detail->author->surname;
исправил для всех полей типа string, которые может заполнить пользователь.
кроме полей типа date, number и проч.

2020-09-02 11:00 UTC, zbralex commented on frontend/views/signup/index.php
> +                        'class' => $model->getErrors('password') ?? 'input-danger'
Идея была в том, что я проверяю массив ошибок по атрибуту и добавляю класс. Немного переделал проверку наличия ошибки, класс надо добавлять, он делает border-color красным

2020-09-02 12:04 UTC, zbralex commented on frontend/views/tasks/view.php
> +$user_data =  User::findOne(Yii::$app->user->id);
исправил

2020-09-02 12:09 UTC, zbralex commented on frontend/views/signup/index.php
> +                        'class' => $model->getErrors('password') ?? 'input-danger'
в итоге так и не смог понять, как проверить, есть ли в текущем поле ошибка, чтобы добавить класс

2020-09-02 12:24 UTC, zbralex commented on src/classes/Task.php
> +            case self::STATUS_PROGRESS and $role == 2:
эти роли у меня записываются в базу. Изначально, я посчитал, что хранить данные в виде числа будет экономичнее с точки зрения занимаемого места. Сделал в виде констант

2020-09-04 06:53 UTC, zbralex commented on frontend/controllers/UsersController.php
> +            FilterUtil::formFilter($formContent, $query);
сделал б)

2020-09-04 06:53 UTC, zbralex commented on src/classes/utils/FilterUtil.php
> +abstract class FilterUtil {
сделал

2020-09-04 10:54 UTC, zbralex commented on src/classes/utils/CreateTaskService.php
> +abstract class CreateTaskService
не изменял, оставил как есть

2020-09-04 10:54 UTC, zbralex commented on frontend/views/tasks/create.php
> + * */
сделал везде во вьюхах

2020-09-15 07:04 UTC, b1rdex requested changes

2020-09-15 07:04 UTC, b1rdex commented on frontend/models/forms/CreateTaskForm.php
>              mkdir($dir, 0777);
Сделай с третьим аргументом true, чтобы создавалась вся структура папок

2020-09-15 07:04 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +            return $this->redirect('/tasks');
Раз уже есть страница просмотра, то делай сразу редирект на просмотр задания. Ну или оставь пока так) не критично

2020-09-15 07:05 UTC, merged