исправляет вывод цены
htmlacademy-yii/164719-task-force-1 pull request #17
Opened 2020-09-15 07:45 UTC by zbralex

2020-10-26 08:01 UTC, b1rdex requested changes

2020-10-26 08:01 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +			$response = Response::findOne(['task_id' => $id, 'user_id' => $user_id]);
Надо убедиться, что оно нашлось

2020-10-26 08:01 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +			sleep(1);
Это зачем?

2020-10-26 08:01 UTC, b1rdex commented on frontend/views/tasks/view.php
>  						->count();
Этот запрос нужно перенести в контроллер. В шаблонах нельзя делать запросы (критерии для защиты)

2020-10-26 08:01 UTC, b1rdex commented on src/classes/Task.php
> +			case self::STATUS_NEW == $this->status and $author === $currentUserId:
Это надо переделать на серию if/elseif, т.к. сейчас тут чисто магия и работает оно, вероятно, неправильно, т.к. switch сравнивает $this->status с этими выражениями приводя тип к bool, т.е. выполнится всегда первый кейс, если (bool)$this->status === true. Извини, до этого не заметил это.

2020-10-26 08:01 UTC, b1rdex commented on src/classes/Task.php
> +			case self::STATUS_NEW == $statusResponse:
Тут тоже переделать

2020-10-26 16:33 UTC, zbralex commented on frontend/controllers/TasksController.php
> +			sleep(1);
здесь я сохраняю статус для отклика, что отклик отклонён. 

Это действие для заказчика в списке откликов.

2020-10-26 16:37 UTC, zbralex commented on frontend/views/tasks/view.php
>  						->count();
Сделал

2020-10-26 16:41 UTC, zbralex commented on frontend/controllers/TasksController.php
> +			$response = Response::findOne(['task_id' => $id, 'user_id' => $user_id]);
сделал проверку

2020-10-26 16:53 UTC, zbralex commented on src/classes/Task.php
> +			case self::STATUS_NEW == $this->status and $author === $currentUserId:
Я перепишу, конечно. Но хочу объяснить, почему я сделал так. 
1. Большое количество if/else по идее должно выноситься в switch.
2. В  switch проверяется, передан ли статус `switch ($this->status) {}`. Он возвращает булев и проваливается в цикл проверок текущего статуса. 

`case self::STATUS_NEW == $this->status` это я нахожу здесь лишним, уберу. По идее, мне проще воспринимать код с блоками условий if/else(-if). Но switch был как-то в самом начале выбран. Перепишу короче :)

2020-10-26 17:55 UTC, zbralex commented on src/classes/Task.php
> +			case self::STATUS_NEW == $statusResponse:
переделал

2020-10-26 17:55 UTC, zbralex commented on src/classes/Task.php
> +			case self::STATUS_NEW == $this->status and $author === $currentUserId:
переделал, запушил всё

2020-10-27 02:15 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +			sleep(1);
Я спрашивал про sleep(), для чего он?

2020-10-27 02:17 UTC, b1rdex commented on src/classes/Task.php
> +			case self::STATUS_NEW == $this->status and $author === $currentUserId:
Смотри, если ты хочешь делать switch(), то пиши тогда вот так:
```php
switch (true) {
	case ...
}
```
Так хотя бы ты явно покажешь, что ищешь ветку, кейс которой true. А сейчас у тебя неявное поведение, которое приводило $this->status в булев тип, т.е. тупо в true.

Насчёт `and/or`: рекомендую всегда использовать только `&&/||`, так не будет проблем с разными приоритетами.

2020-10-27 02:17 UTC, b1rdex commented on src/classes/Task.php
> +			case self::STATUS_NEW == $statusResponse:
То же самое про switch(true)

2020-11-07 06:12 UTC, zbralex commented on frontend/controllers/TasksController.php
> +			sleep(1);
sleep() я как бы имитировал задержку, т.к. быстро происходил запрос. Убрал

2020-11-09 10:59 UTC, b1rdex requested changes

2020-11-09 10:59 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +			if (isset($response)) {
Тут надо поменять наоборот. Если его нет, тогда ошибка
```suggestion
			if (null === $response) {
```

2020-11-09 10:59 UTC, b1rdex commented on frontend/views/tasks/view.php
> +									var_dump($detail->author->role_id);
```suggestion
```

2020-11-09 11:01 UTC, merged