restful api
htmlacademy-yii/164719-task-force-1 pull request #19
Opened 2020-11-18 18:53 UTC by zbralex

2020-12-08 02:27 UTC, b1rdex requested changes

2020-12-08 02:27 UTC, b1rdex commented on frontend/web/js/messenger.js
> +      this.api_url = '/message/api/messages' + '/list/' + this.task;
Лучше оставить `/api/messages?task_id=`, могут на проверке докопаться. Для такого роута будет `actionView`.

И ещё учти сразу https://up.htmlacademy.ru/yii/1/criteries#d17

2020-12-08 02:27 UTC, b1rdex commented on frontend/modules/api/message/controllers/MessagesController.php
> +
1. Поудаляй все лишние экшны и шаблоны, пожалуйста. Так будет проще ориентироваться что тут происходит
2. https://www.yiiframework.com/doc/api/2.0/yii-rest-activecontroller
В самом начале написано, что умеет делать ActiveController. Нам нужно переопределить view (т.к. вернём массив, а не одно сообщение) и create (т.к. создание тоже нужно дорабоать).
Поэтому, нужно убрать готовые реализации view и create: нужно переопределить метод actions(), и вернуть `parent::actions();` без ключей `create` и `view`.

2020-12-10 12:45 UTC, zbralex commented on frontend/web/js/messenger.js
> +      this.api_url = '/message/api/messages' + '/list/' + this.task;
Про версионирование в учебнике ни слова ( Читал только об этом. 

Переделаю  this.api_url = '/message/api/messages' + '?task_id=' + this.task;

2020-12-10 13:32 UTC, zbralex commented on frontend/modules/api/message/controllers/MessagesController.php
> +
1. Экшны я поудалял лишние и вставил свой новый экшн. 
2. НИчего не понял со второго предложения.

2020-12-11 02:05 UTC, b1rdex commented on frontend/web/js/messenger.js
> +      this.api_url = '/message/api/messages' + '/list/' + this.task;
Суть в том, что url должен быть таким: `/api/v1/messages?task_id=` или таким: `/api/messages?v=1&task_id=1`
Проще сделать с префиксом `/v1/`, для этого просто в модуле api сделай модуль v1 и в нём уже выполняй задание :)

2020-12-11 02:06 UTC, b1rdex commented on frontend/web/js/messenger.js
> +      this.api_url = '/message/api/messages' + '/list/' + this.task;
Увидел что ты уже сделал модуль 👍

2020-12-11 02:12 UTC, b1rdex commented on frontend/web/js/messenger.js
> +      this.api_url = '/message/api/messages' + '?task_id=' + this.task;
/api/v1/messages?task_id=

2020-12-11 02:14 UTC, b1rdex requested changes

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/message/_form.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/message/create.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/message/index.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/message/update.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/message/view.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/messages/_form.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/messages/create.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/messages/index.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/messages/update.php
> +<?php
Этот файл лишний?

2020-12-11 02:14 UTC, b1rdex commented on frontend/views/messages/view.php
> +<?php
Этот файл лишний?

2020-12-11 09:13 UTC, zbralex commented on frontend/views/message/_form.php
> +<?php
я даже не заметил их, видать при генерации через gii добавились. Удалил

2021-02-08 14:26 UTC, b1rdex requested changes
В целом, задача решена. Как будет оценено на защите решение в MessagesController и изменение скрипта – не берусь судить. По мне, так переопределение prepareDataProvider выглядит как супер костыль. Чистое решение задачи предполагает удаление методов create и view из actions и добавление своих actionCreate(int $id) и actionView(int $id) – передача task id уже есть в скрипте изначально.

Весь код контроллера супер прост. Я вроде бы это уже тебе объяснял и показывал частями. Привожу полный код контроллера для ознакомления:
```php
    public function actions(): array
    {
        $actions = parent::actions();

        unset($actions['view'], $actions['create']);

        return $actions;
    }

    public function actionCreate(int $id)
    {
        $content = json_decode(Yii::$app->getRequest()->getRawBody());
        $message = new Messages();
        $message->user_id = Yii::$app->user->getId();
        $message->task_id = $id;
        $message->message = $content->message;
		$message->save();
        Yii::$app->getResponse()->setStatusCode(201);

        return $message;
    }

    public function actionView(int $id)
    {
        return Messages::find()->where(['task_id' => $id])->all();
    }
```

Переделывать не заставляю, это на твоё усмотрение. Обязательными к исправлению только два комментария по коду.

2021-02-08 14:26 UTC, b1rdex commented on frontend/modules/api/v1/messages/controllers/MessagesController.php
> +        if ($_GET) {
По критериям запрещено использовать суперглобальные массивы

2021-02-08 14:26 UTC, b1rdex commented on frontend/web/js/messenger.js
> +      this.api_url = '/api/messages';
/api/v1/messages

2021-02-09 19:17 UTC, zbralex commented on frontend/modules/api/v1/messages/controllers/MessagesController.php
> +        if ($_GET) {
Пожалуйста, не сочти это тупостью или занудством, я и сам не рад :(
```
public function actions(): array
    {
        $actions = parent::actions();

        unset($actions['view'], $actions['create']);

        return $actions;
    }

    public function actionCreate(int $id)
    {
        $content = json_decode(Yii::$app->getRequest()->getRawBody());
        $message = new Messages();
        $message->user_id = Yii::$app->user->getId();
        $message->task_id = $id;
        $message->message = $content->message;
		$message->save();
        Yii::$app->getResponse()->setStatusCode(201);

        return $message;
    }

    public function actionView(int $id)
    {
        return Messages::find()->where(['task_id' => $id])->all();
    }
```
Код этого контроллера не работает, я тупо скопипастил его и он не отрабатывает. 
В приведённом тобой коде сперва сбрасывается поведение экшнов actionView и actionCreate.

Далее, для получения списка сообщений переопределяется метод **actionView**. Этот метод возвращает абсолютно все сообщения, я не менял в методе ничего, за исключением подключения модели. Открываю консоль и вижу, что используется роут для GET-запроса сообщений _api/v1/messages/index_ .

Метод **actionCreate**. Если в код мессенджера не добавлять дополнительный участок для роута _/create_, то метод actionCreate не отработает, потому что в **actionCreate** - **create** это и есть часть маршрута. Если я в код js добавлю его, то **actionCreate** отработает, получится так _this.api_url + '/create'_:
```
fetch(this.api_url + '/create', {
        method: 'POST',
        body: JSON.stringify({message: this.message, task_id: this.task})
      })
```
...но по условию этого делать нельзя. 
Код мессенджера я вернул в исходное состояние, последние изменения пришли в слак.
Я хочу предложить следующее решение с обоснованием. 
```
public function actions():array
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions;
    }
```
сбрасываю дефолтное поведение и далее возвращаю список сообщений для GET-запроса 
с помощью $request->isGet и создаю новые сообщения, если запрос POST ($request->isPost)

    public function actionIndex(int $task_id = null)
    {
        $request = Yii::$app->request;
        if ($request->isGet) {
            if (!$task_id) {
                throw new ForbiddenHttpException();
            }
            return Message::find()->where(['task_id' => $task_id])->all();
        }


        if ($request->isPost) {
            $message = new Message();

            $message->user_id = Yii::$app->user->getId();
            $message_body = json_decode(Yii::$app->getRequest()->getRawBody(), true);
            $message->task_id = $message_body['task_id'];
            $message->text = $message_body['message'];

            $message->save(false);
            Yii::$app->getResponse()->setStatusCode(201);
            return $message;
        }
    }


Далее я разрешаю посылать запросы к индексному пути _/api/v1/messages_
`protected function verbs()
    {
        return [
            'index' => ['GET', 'HEAD', 'POST'],
        ];
    }`

Метод работает, однако в нем нет защиты. Добавляю проверку доступа в начало метода 
```
if (!\Yii::$app->user->id)
                throw new \yii\web\ForbiddenHttpException(sprintf('Доступ только для авторизованных пользователей.', $action));
```
Итого, код моего рабочего контроллера: 
```
class MessagesController extends ActiveController
{
    public $modelClass = Message::class;
    public $allowedActions = ['index'];
    public $enableCsrfValidation = false;


    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);


        return $actions;
    }

    public function actionIndex(int $task_id = null)
    {
        if (!\Yii::$app->user->id)
            throw new \yii\web\ForbiddenHttpException(sprintf('Доступ только для авторизованных пользователей.'));
        
        $request = Yii::$app->request;
        if ($request->isGet) {
            if (!$task_id) {
                throw new ForbiddenHttpException();
            }
            return Message::find()->where(['task_id' => $task_id])->all();
        }


        if ($request->isPost) {
            $message = new Message();

            $message->user_id = Yii::$app->user->getId();
            $message_body = json_decode(Yii::$app->getRequest()->getRawBody(), true);
            $message->task_id = $message_body['task_id'];
            $message->text = $message_body['message'];

            $message->save(false);
            Yii::$app->getResponse()->setStatusCode(201);
            return $message;
        }
    }
    
    protected function verbs()
    {
        return [
            'index' => ['GET', 'HEAD', 'POST'],
        ];
    }
}
```

2021-02-10 01:59 UTC, b1rdex commented on frontend/modules/api/v1/messages/controllers/MessagesController.php
> +        if ($_GET) {
Да, как вариант. Либо через роутинг можно разрулить:
```
'patterns' => [
    'GET {id}' => 'view',
    'POST {id}' => 'create',
],
```

2021-02-11 03:01 UTC, b1rdex approved these changes

2021-02-11 03:01 UTC, merged